### PR TITLE
Add client testing and circleci config

### PR DESCRIPTION
**Pull request by willdunklin**

### CODE REVIEW

**Comment by manthey** [comment]
We never authenticate after the initial import, which means downloads fail after restarting Girder.

**Comment by manthey** [comment]
The requirement for a base path seems a little odd, since a blank value and `/` work functionally the same.  Until we can import collections and users (which would be a good thing to add), the import UI should say it only works on folders.

**Comment by manthey** [comment]
In order to proceed with testing, I added an authenticate line as part of `__init__`.  Looking at the remote system, we get a _lot_ of authentications when reading a large_image.  This means that we should only authenticate if we haven't done so already and if need to (for downloading).

An alternative would be to move getting the girder client outside of the adapter class and use `@functools.lru_cache` to cache the client.  But the lru_cache would need the parameters to be hashable (like using a namedtuple rather than a dictionary).  This might be something like:

```
@functools.lru_cache
def _getClient(assetstore_meta):
    meta = assetstore_meta._asdict()
    if 'url' in meta:
        client = GirderClient(apiUrl=meta['url'])
        if meta.get('apiKey'):
            client.authenticate(apiKey=meta['apiKey'])
        elif meta.get('username') and meta.get('password'):
            client.authenticate(username=meta['username'], password=meta['password'])
        return client
    return None
```

And then doing something like `self.client = _getClient(collections.namedtuple('ClientTuple', sorted(self.assetstore_meta))(**self.assetstore_meta))`

**Comment by willdunklin** [comment]
@manthey I made some changes that should address the points you raised. I added a `lru_cache` function similar to what you described in your comment.

> We never authenticate after the initial import, which means downloads fail after restarting Girder.

Are you still able to replicate this after adding these changes? Maybe I'm missing the details of your setup but I haven't been able to reproduce following the changes I made in these commits. Do you think you could share the steps for how you were triggering this failure (if it still persists)?

**Comment by manthey** [comment]
> Are you still able to replicate this after adding these changes? Maybe I'm missing the details of your setup but I haven't been able to reproduce following the changes I made in these commits. Do you think you could share the steps for how you were triggering this failure (if it still persists)?

Now that `self.client` is a `@property` that gets the client if needed, the problem goes away.  Prior to that change, the issue would be that you could import data from another girder instance, restart the current girder instance, and then download wouldn't work because self.client wasn't set.

**Pull request merged**
